# Generated by Django 5.2.9 on 2026-01-05 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encryption_type', models.CharField(choices=[('AES', 'AES-256-CBC (Simétrico)'), ('RSA', 'RSA-2048 (Asimétrico)'), ('HYBRID', 'Híbrido (RSA + AES)')], default='AES', max_length=10)),
                ('ciphertext', models.TextField(help_text='Contenido del mensaje cifrado en base64')),
                ('iv', models.CharField(blank=True, help_text='IV para AES en base64', max_length=64)),
                ('encrypted_key', models.TextField(blank=True, help_text='Clave AES cifrada con RSA (para híbrido)')),
                ('signature', models.TextField(blank=True, help_text='Firma digital del mensaje')),
                ('key_size', models.IntegerField(default=256)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'db_table': 'messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SharedKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_for_user1', models.TextField(help_text='Clave cifrada con la clave pública del user1')),
                ('key_for_user2', models.TextField(help_text='Clave cifrada con la clave pública del user2')),
                ('key_size', models.IntegerField(default=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Clave Compartida',
                'verbose_name_plural': 'Claves Compartidas',
                'db_table': 'shared_keys',
            },
        ),
    ]
