# Generated by Django 5.2.9 on 2026-01-05 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('LOGIN_FAILED', 'Login fallido'), ('REGISTER', 'Registro'), ('KEY_GENERATE', 'Generación de claves'), ('KEY_ROTATE', 'Rotación de claves'), ('ENCRYPT', 'Cifrado'), ('DECRYPT', 'Descifrado'), ('SIGN', 'Firma digital'), ('VERIFY', 'Verificación'), ('MESSAGE_SEND', 'Mensaje enviado'), ('MESSAGE_READ', 'Mensaje leído')], max_length=20)),
                ('severity', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('BRUTE_FORCE', 'Ataque de fuerza bruta'), ('SUSPICIOUS_ACTIVITY', 'Actividad sospechosa'), ('UNAUTHORIZED_ACCESS', 'Acceso no autorizado'), ('KEY_COMPROMISE', 'Posible compromiso de clave')], max_length=30)),
                ('severity', models.CharField(default='WARNING', max_length=10)),
                ('description', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'security_alerts',
                'ordering': ['-created_at'],
            },
        ),
    ]
